/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Losson (https://sketchfab.com/losson)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/buick-regal-gnx-1987-524dadfc588a4554892879dd8217d746
Title: Buick Regal GNX 1987
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gnx.glb')
  return (
    <group {...props} dispose={null}>
      <lineSegments
        geometry={nodes.Object_2.geometry}
        material={materials.PaletteMaterial001}
        position={[3.138, 0.384, -1.644]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.95}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3.geometry}
        material={materials.PaletteMaterial002}
        position={[0.974, 0.826, -1.686]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.99}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial003}
        position={[0.937, 0.589, -1.655]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.84}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.PaletteMaterial004}
        position={[-1.637, 0.707, -1.716]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.968}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.PaletteMaterial005}
        position={[1.003, 1.084, -1.717]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.78}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.PaletteMaterial006}
        position={[3.672, 0.822, -1.637]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.014}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.PaletteMaterial001}
        position={[0.994, 0.777, -1.681]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.847}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.PaletteMaterial007}
        position={[0.895, 0.389, -1.676]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.801}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_58.geometry}
        material={materials.PaletteMaterial008}
        position={[-1.737, 0.566, -1.716]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.005}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_59.geometry}
        material={materials.PaletteMaterial009}
        position={[1.864, 1.187, -1.67]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.854}
      />
      <lineSegments
        geometry={nodes.Object_63.geometry}
        material={materials.PaletteMaterial010}
        position={[0.895, 0.389, -1.676]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.718}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_64.geometry}
        material={materials.PaletteMaterial010}
        position={[0.741, 0.389, -1.679]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.675}
      />
      <lineSegments
        geometry={nodes.Object_68.geometry}
        material={materials.PaletteMaterial011}
        position={[2.455, 0.354, -1.655]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.702}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_69.geometry}
        material={materials.PaletteMaterial011}
        position={[0.893, 0.387, -1.679]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.02}
      />
    </group>
  )
}

useGLTF.preload('/gnx.glb')